30 version bump
datasciencecampus/chrono_lens pull request #31
Opened 2021-12-15 09:31 UTC by IanGrimstead

* Version bump to `lxml` library c/o dependabot
* Update to R scripts, to reduce memory usage
* Correction to `runner-startup.sh` to ensure QA files are sent to GCP bucket

2021-12-15 09:45 UTC, IanGrimstead commented
This will become release `v1.1.1` (cute!) as its a minor fix rather than new functionality

2021-12-16 10:55 UTC, Ryan2Y79 requested changes
Hey, just spotted a single spelling mistake in the README. Just amend and all is good.

2021-12-16 10:55 UTC, Ryan2Y79 commented on cloud/vm/README_RScripts.md
> +their corresponding latest date in each dataset. This file isused so the R script knows which locations to download
'is used' not 'isused'

2021-12-16 11:07 UTC, IanGrimstead commented on cloud/vm/README_RScripts.md
> +their corresponding latest date in each dataset. This file isused so the R script knows which locations to download
Good spot!

2021-12-16 11:42 UTC, merged